### ISSUE TITLE
watch null EMFILE

### ISSUE THREAD

**Issue by huxiaohuxiao** [dragonwong/rnxDemo#1]
ERROR  watch null EMFILE
{"code":"EMFILE","errno":"EMFILE","syscall":"watch null","filename":null}
Error: watch null EMFILE
    at exports._errnoException (util.js:860:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1296:21)

**Comment by dragonwong** [comment]
@huxiaohuxiao 抱歉，这个项目不维护了，目前依赖的 [rnx-ui](https://github.com/rnxteam/rnx-ui) 已经迁出了并继续维护，其他依赖还在计划中。如果你有其他需求请随时告知。😀

**Comment by huxiaohuxiao** [comment]
watchman版本问题 升级4.7.0 ok
